version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-tasks
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:appkey
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=test1
      - DB_USERNAME=root
      - DB_PASSWORD=Ta!3243dfgert45##22

  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ta!3243dfgert45##22
      MYSQL_DATABASE: laravel
      MYSQL_USER: test1
      MYSQL_PASSWORD: Ta!3243dfgert45##22
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
