name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the code from the GitHub repository

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3  # Sets up SSH key for deployment
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use your private SSH key

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $SERVER_USER@$SERVER_IP "
          cd /path/to/your/project &&
          git pull origin master &&
          composer install --no-dev &&
          php artisan migrate --force"
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
